server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos12345
    
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    
  security:
    oauth2:
      client:
        provider: 
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao: 
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri:  https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            
        registration: 
          google: 
            client-id: 1035052018334-gplfpt6h3gc4naqgi7ahmchn6jeoq0da.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook: 
            client-id: 933385633996077
            client-secret: 405d54298f4dc23675498bb3d7c86803
            scope: 
            - email
            - public_profile
          naver:
            client-id: fkEW6iOxN8oYuC6kD0pN
            client-secret: wYQ7OxzD3h
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code 
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
          kakao:
            client-id: 7e25a8cecfdcd4aa062c09f547f99a1a
            client-secret: 3YTcfs6guplTmOVtLW1sQ4Z5oKjQ9vW1
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST
            scope:
             - profile_nickname
             - profile_image

  properties:
    hibernate:
      format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false
cos:
  key: cos1234